### ISSUE TITLE
pinch of yum

### ISSUE THREAD

**Issue by elbrenn** [boonepeter/some-recipes#4]
Suggestion for a blog to support 
https://pinchofyum.com 😋

**Comment by elbrenn** [comment]
retried, but hit a few errors
<img width="1430" alt="Screen Shot 2020-06-30 at 7 48 29 PM" src="https://user-images.githubusercontent.com/34719884/86187874-e8525b80-bb0a-11ea-813a-3d920ef2d6f6.png">

**Comment by boonepeter** [comment]
Thanks for the suggestion! I changed up the [parsing API](https://github.com/boonepeter/recipe-parser) to support more recipe sites (if they include their recipe as a `Recipe` from schema.org). So pinch of yum is now supported! And I fixed the other issue you pointed out. Thanks @elbrenn!
